const state={committee:'IRAC',data:null,search:'',group:'ALL',screen:'home',deferredPrompt:null};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const splitAI=s=>String(s||'').split(';').map(x=>x.trim()).filter(Boolean);
async function load(){state.data=await (await fetch('data/moa_master_2026.json')).json();updateHomeStats();render();}
function rows(){return state.data?.records?.[state.committee]||[]}
function normalize(r){if(state.committee==='IRAC')return{code:r[1],name:r[2],sub:r[3],chem:r[4],ai:splitAI(r[5]),cat:r[6]};if(state.committee==='FRAC')return{code:r[1],name:r[2],sub:r[3],chem:r[4],ai:splitAI(r[5]),cat:r[6],risk:r[7]};return{code:r[1],legacy:r[2],name:r[3],chem:r[4],ai:splitAI(r[5])}}
function filtered(){const q=state.search.toLowerCase();return rows().map(normalize).filter(x=>{const hay=[x.code,x.legacy,x.name,x.sub,x.chem,x.cat,x.risk,...x.ai].filter(Boolean).join(' ').toLowerCase();return(!q||hay.includes(q))&&(state.group==='ALL'||x.code===state.group)})}
function groups(){return[...new Set(rows().map(normalize).map(x=>x.code))].filter(Boolean)}
function updateHomeStats(){const all=['IRAC','FRAC','HRAC'].flatMap(c=>state.data?.records?.[c]||[]);const ai=[...new Set(all.flatMap(r=>splitAI(r[5])))];$('#homeGroups').textContent=all.length;$('#homeAI').textContent=ai.length}
function render(){if(state.screen!=='explore')return;$('#exploreTitle').textContent=state.committee;$('#exploreSub').textContent=state.committee==='IRAC'?'Insecticide · Acaricide · Nematicide':state.committee==='FRAC'?'Fungicide resistance & mode of action':'Herbicide mode of action';$('#activeCommittee').textContent=state.committee+' 2026';const gs=groups();$('#groupFilters').innerHTML='<button class="chip active" data-group="ALL">Semua</button>'+gs.map(g=>`<button class="chip" data-group="${esc(g)}">${esc(g)}</button>`).join('');$$('.chip').forEach(b=>b.addEventListener('click',()=>{state.group=b.dataset.group;$$('.chip').forEach(x=>x.classList.toggle('active',x===b));renderList()}));renderList();}
function renderList(){const list=filtered();$('#resultCount').textContent=list.length;$('#cards').innerHTML=list.map((x,i)=>`<button class="moa-card" data-i="${i}"><div class="code">${esc(state.committee)}<strong>${esc(x.code)}</strong>${x.legacy?`<small>Legacy ${esc(x.legacy)}</small>`:''}</div><div class="moa-main"><h3>${esc(x.name)}</h3><p>${esc(x.chem||x.sub||'')}</p><div class="ai-row">${x.ai.slice(0,4).map(a=>`<span>${esc(a)}</span>`).join('')}${x.ai.length>4?`<span>+${x.ai.length-4}</span>`:''}</div></div><span class="arrow">›</span></button>`).join('')||'<div class="empty">Tidak ada data yang cocok.</div>';$$('.moa-card').forEach(b=>b.addEventListener('click',()=>openDetail(list[+b.dataset.i])))}
function openDetail(x){$('#detail').innerHTML=`<div class="detail-backdrop" id="detailBackdrop"></div><aside class="detail-sheet"><button class="close" id="closeDetail">×</button><div class="detail-code">${esc(state.committee)} · ${esc(x.code)}${x.legacy?` · Legacy ${esc(x.legacy)}`:''}</div><h2>${esc(x.name)}</h2>${x.sub?`<p class="muted">${esc(x.sub)}</p>`:''}<div class="detail-grid"><div><label>Mode / target</label><strong>${esc(x.name)}</strong></div><div><label>Kelas kimia</label><strong>${esc(x.chem||'—')}</strong></div>${x.cat?`<div><label>Kategori</label><strong>${esc(x.cat)}</strong></div>`:''}${x.risk?`<div><label>Resistance risk</label><strong>${esc(x.risk)}</strong></div>`:''}</div><h3>Active ingredients</h3><div class="ai-list">${x.ai.map(a=>`<span>${esc(a)}</span>`).join('')}</div><p class="source-note">Referensi klasifikasi ${esc(state.committee)}. Gunakan sebagai referensi teknis dan selalu cek label serta registrasi lokal sebelum aplikasi.</p></aside>`;$('#detailBackdrop').addEventListener('click',closeDetail);$('#closeDetail').addEventListener('click',closeDetail)}
function closeDetail(){$('#detail').innerHTML=''}
function showScreen(id){$$('.screen').forEach(s=>s.classList.toggle('active-screen',s.id===id));$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===id));state.screen=id;if(id==='explore')render();window.scrollTo({top:0,behavior:'smooth'})}
function setCommittee(c){state.committee=c;state.group='ALL';state.search='';$('#search').value='';$$('.committee-tabs button').forEach(x=>x.classList.toggle('active',x.dataset.c===c));render()}
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.committee)setCommittee(b.dataset.committee);showScreen(b.dataset.go)}));
$$('.committee-tabs button').forEach(b=>b.addEventListener('click',()=>setCommittee(b.dataset.c)));
$('#search').addEventListener('input',e=>{state.search=e.target.value;renderList()});$('#clearSearch').addEventListener('click',()=>{$('#search').value='';state.search='';renderList()});$('#focusSearch').addEventListener('click',()=>$('#search').focus());
$('#menuBtn').addEventListener('click',()=>showScreen('menu'));$('#menuTheme').addEventListener('click',()=>document.documentElement.classList.toggle('dark'));$('#themeBtn').addEventListener('click',()=>document.documentElement.classList.toggle('dark'));
$('#installBtn').addEventListener('click',async()=>{if(state.deferredPrompt){await state.deferredPrompt.prompt();state.deferredPrompt=null}else alert('Gunakan menu Chrome → Tambahkan ke layar utama untuk memasang aplikasi.')});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredPrompt=e;$('#installBtn').hidden=false});window.addEventListener('appinstalled',()=>$('#installBtn').hidden=true);
if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});load().catch(e=>console.error(e));
